spring:
  kafka:
    bootstrap-servers: 192.168.117.128:9092
    # \u751F\u4EA7\u8005\u7684\u914D\u7F6E\u53E6\u4E00\u4E2A\u9879\u76EE springbootKafka \u4E2D
    consumer:
      group-id: test
      enable-auto-commit: true
      auto-commit-interval: 1000
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
